import { appendFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export type AuditEvent = "init" | "use" | "call" | "distill" | "publish-check" | "doctor" | "offboard" | "query" | "skill-validate";

export interface AuditEntry {
  event: AuditEvent;
  timestamp: string;     // ISO 8601, generated by helper if not provided
  context?: string;      // active context name when entry written
  payload?: Record<string, unknown>;
}

const AUDIT_DIR = join(homedir(), ".pdctx", "audit");

export function log(entry: Omit<AuditEntry, "timestamp"> & { timestamp?: string }): void {
  const timestamp = entry.timestamp ?? new Date().toISOString();
  const full: AuditEntry = { ...entry, timestamp };

  // Derive YYYY-MM from the resolved timestamp (handles caller-supplied timestamps too)
  const month = timestamp.slice(0, 7); // "2026-04"
  const file = join(AUDIT_DIR, `${month}.jsonl`);

  mkdirSync(AUDIT_DIR, { recursive: true });
  appendFileSync(file, JSON.stringify(full) + "\n");
}
