import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { log as auditLog } from "../engine/audit.ts";

const PDCTX_HOME = join(homedir(), ".pdctx");

const DEFAULT_CONFIG = `# pdctx CONFIG.toml
# Generated by \`pdctx init\` — edit freely. Validated against schema on load.

schema_version = 1

[active]
context = ""  # set by \`pdctx use <ctx>\`

[stack.sources]
# Each entry points to a stack repo (folder with contexts/ + skills/ + agents/).
# pdctx loads contexts/ from each in order, later sources override earlier.
# pandastack         = "~/site/skills/pandastack"
# pandastack-private = "~/site/skills/pandastack-private"

[runtimes]
# Which runtimes pdctx will sync to on \`pdctx use\`.
claude = true
codex  = true
# hermes = false  # v0.5
# gemini = false  # v0.5

[hooks]
# on_context_activate = ""
# on_context_deactivate = ""
`;

export async function runInit(): Promise<void> {
  const created: string[] = [];
  const skipped: string[] = [];

  if (!existsSync(PDCTX_HOME)) {
    mkdirSync(PDCTX_HOME, { recursive: true });
    created.push(PDCTX_HOME);
  } else {
    skipped.push(PDCTX_HOME);
  }

  for (const sub of ["memory", "audit", "state", "contexts"]) {
    const path = join(PDCTX_HOME, sub);
    if (!existsSync(path)) {
      mkdirSync(path, { recursive: true });
      created.push(path);
    } else {
      skipped.push(path);
    }
  }

  const configPath = join(PDCTX_HOME, "CONFIG.toml");
  if (!existsSync(configPath)) {
    writeFileSync(configPath, DEFAULT_CONFIG);
    created.push(configPath);
  } else {
    skipped.push(configPath);
  }

  console.log("pdctx init —", created.length, "created,", skipped.length, "already existed");
  for (const p of created) console.log("  + " + p);
  for (const p of skipped) console.log("  = " + p);
  console.log("");
  console.log("next: edit ~/.pdctx/CONFIG.toml [stack.sources] to point at your stacks.");

  auditLog({
    event: "init",
    payload: {
      created: created.length,
      skipped: skipped.length,
      paths_created: created,
    },
  });
}
